= Task 3 - File Scanner via FJP

Cost: 1 points.

Create CLI application that scans a specified folder and provides detailed statistics:

1. File count.
2. Folder count.
3. Size (sum of all files size) (similar like Windows context menu Properties). Since the folder may contain huge number of files the scanning process should be executed in a separate thread displaying an informational message with some simple animation like progress bar in CLI (up to you, but I'd like to see that task is in progress).

Once task is done, the statistics should be displayed in the output immediately. Additionally, there should be ability to interrupt the process pressing some reserved key (for instance c). Of course, use Fork-Join Framework for implementation parallel scanning.

[source,text]
----
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.0.4)

shell:>scan /Users
2023-03-15T11:26:05.047+02:00  INFO 23071 --- [           main] Benchmark                                : scan (/Users)
2023-03-15T11:27:18.949+02:00  INFO 23071 --- [           main] Benchmark                                : scan successful processed.
2023-03-15T11:27:18.949+02:00  INFO 23071 --- [           main] Benchmark                                : scan exec time: 73,901ms
File count: 1,222,854
Dirs count: 222,847
Total size: 208,665,322,413

shell:>
----

[source,text]
----
shell:>scan /usr
2023-03-15T12:53:39.142+02:00  INFO 25413 --- [           main] Benchmark                                : scan (/usr)
Processed: 0
Processed: 16,391
Processed: 28,500
Processed: 41,795
Processed: 55,967
2023-03-15T12:53:41.671+02:00  INFO 25413 --- [           main] Benchmark                                : scan successful processed.
2023-03-15T12:53:41.672+02:00  INFO 25413 --- [           main] Benchmark                                : scan exec time: 2,528ms
File count: 72,323
Dirs count: 7,784
Total size: 12,254,622,073
----

[source,text]
----
shell:>scan /opt
2023-03-15T13:04:40.757+02:00  INFO 25728 --- [           main] Benchmark                                : scan (/opt)
Processed: 0
c
2023-03-15T13:04:43.077+02:00  INFO 25728 --- [           main] Benchmark                                : scan successful processed.
2023-03-15T13:04:43.078+02:00  INFO 25728 --- [           main] Benchmark                                : scan exec time: 2,319ms
File count: 53,523
Dirs count: 3,222
Total size: 2,665,879,489

shell:>scan /opt
2023-03-15T13:04:54.795+02:00  INFO 25728 --- [           main] Benchmark                                : scan (/opt)
Processed: 0
s
Interrupting...
2023-03-15T13:04:56.196+02:00  INFO 25728 --- [           main] Benchmark                                : scan successful processed.
2023-03-15T13:04:56.197+02:00  INFO 25728 --- [           main] Benchmark                                : scan exec time: 1,399ms
Scan interrupted.
shell:>
----
